follow_symlinks = false

# I used to add git information to the prompt,
# but it turns out it slows down the prompt in very large repository like nixpkgs.
#
# I used to emit OSC 7 in the prompt, but it should be the job of the shell to do so.
# For example, fish shell does that since 4.0.
# See https://fishshell.com/docs/current/relnotes.html#fish-4-0-0-released-february-27-2025
#
# Fish shell claims that it writes OSC 133 to indicate the start of a prompt and the end of a prompt.
# However, in my testing with fish@4.6.0, it does not write OSC 133 that tmux can understand.
# So we do it here.
#
# In my testing with nu@0.112.2, it emits OSC 133 natively.
# It seems that it is not harmful to emit OSC 133 in starship though.
format = "${custom.osc_133_prompt_start}$jobs$kubernetes$python$direnv$shell@$shlvl\n$status ${custom.osc_133_prompt_end}"
# In my testing with nu@0.112.2, if add_newline is true, the position of OSC 133 prompt start omitted by nushell is before the newline, which is incorrect.
# Therefore, it is better to turn this off.
add_newline = false

[character]
disabled = false
error_symbol = "[I](bold green)"
format = "$symbol"
success_symbol = "[I](bold green)"
vimcmd_replace_one_symbol = "[R](bold green)"
vimcmd_replace_symbol = "[R](bold cyan)"
vimcmd_symbol = "[N](bold red)"
vimcmd_visual_symbol = "[V](bold purple)"

[direnv]
disabled = false
format = "[$loaded]($style)"
loaded_msg = "(direnv)"
unloaded_msg = ""

[jobs]
symbol_threshold = 1
number_threshold = 1
format = "[\\($number$symbol\\)]($style)"

[kubernetes]
disabled = false
format = "[\\($context\\)]($style)"

[python]
disabled = false
format = "[\\($virtualenv\\)]($style)"

[shell]
disabled = false
format = "[$indicator]($style)"
bash_indicator = "bash"
elvish_indicator = "elvish"
fish_indicator = "fish"
nu_indicator = "nu"
unknown_indicator = "unknown"

[shlvl]
disabled = false
format = "[$shlvl](bold yellow)"
threshold = 0

[status]
disabled = false
format = "$symbol"
not_executable_symbol = "[$status \\$](bold red)"
not_found_symbol = "[$status \\$](bold red)"
sigint_symbol = "[$status \\$](bold red)"
signal_symbol = "[$status \\$](bold red)"
success_symbol = "\\$"
symbol = "[$status \\$](bold red)"

[custom.osc_133_prompt_start]
disabled = false
when = 'true'
unsafe_no_escape = true
format = "$output"
command = ''' printf "\033]133;A\007" '''

[custom.osc_133_prompt_end]
disabled = false
when = 'true'
unsafe_no_escape = true
format = "$output"
command = ''' printf "\033]133;B\007" '''
