TWO_DECIMAL_CURRENCIES: frozenset[str] = frozenset(
    (
        "AED",
        "AFN",
        "ALL",
        "AMD",
        "ANG",
        "AOA",
        "ARS",
        "AUD",
        "AWG",
        "AZN",
        "BAM",
        "BBD",
        "BDT",
        "BMD",
        "BND",
        "BOB",
        "BRL",
        "BSD",
        "BWP",
        "BYN",
        "BZD",
        "CAD",
        "CDF",
        "CHF",
        "COP",
        "CRC",
        "CVE",
        "CZK",
        "DOP",
        "DZD",
        "EGP",
        "ETB",
        "EUR",
        "FJD",
        "FKP",
        "GEL",
        "GIP",
        "GMD",
        "GTQ",
        "GYD",
        "HKD",
        "HNL",
        "HTG",
        "HUF",
        "IDR",
        "ILS",
        "INR",
        "ISK",
        "JMD",
        "KES",
        "KGS",
        "KHR",
        "KYD",
        "KZT",
        "LAK",
        "LBP",
        "LKR",
        "LRD",
        "LSL",
        "MAD",
        "MDL",
        "MKD",
        "MMK",
        "MNT",
        "MOP",
        "MUR",
        "MVR",
        "MWK",
        "MXN",
        "MYR",
        "MZN",
        "NAD",
        "NGN",
        "NIO",
        "NPR",
        "NZD",
        "PAB",
        "PEN",
        "PGK",
        "PHP",
        "PKR",
        "PLN",
        "QAR",
        "RON",
        "RSD",
        "RUB",
        "SAR",
        "SBD",
        "SCR",
        "SEK",
        "SGD",
        "SHP",
        "SLE",
        "SOS",
        "SRD",
        "STD",
        "SZL",
        "THB",
        "TJS",
        "TOP",
        "TRY",
        "TTD",
        "TWD",
        "TZS",
        "UAH",
        "USD",
        "UYU",
        "UZS",
        "WST",
        "XCD",
        "XCG",
        "YER",
        "ZAR",
        "ZMW",
    )
)

ZERO_DECIMAL_CURRENCIES: frozenset[str] = frozenset(
    (
        "BIF",
        "CLP",
        "DJF",
        "GNF",
        "JPY",
        "KMF",
        "KRW",
        "MGA",
        "PYG",
        "RWF",
        "UGX",
        "VND",
        "VUV",
        "XAF",
        "XOF",
        "XPF",
    )
)

SPECIAL_CASES_CURRENCIES: frozenset[str] = frozenset(
    (
        "ISK",
        "HUF",
        "TWD",
        "UGX",
    )
)


def get_decimal_places(currency: str) -> int | None:
    if currency in SPECIAL_CASES_CURRENCIES:
        return 0
    if currency in ZERO_DECIMAL_CURRENCIES:
        return 0
    if currency in TWO_DECIMAL_CURRENCIES:
        return 2
    return None
