{
  pkgs,
  lib,
  ...
}:
{
  system.stateVersion = "25.11";

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  # This was generated by nixos-generate-config, and then modified.
  # 1. Removed reference to https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/scan/not-detected.nix
  #    and place its content `hardware.enableRedistributableFirmware = true;` inline.
  # 2. Set updateMicrocode to true
  # 3. Use /dev/disk/by-label instead of /dev/disk/by-uuid
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  boot.initrd.availableKernelModules = [
    "xhci_pci" # USB 3.0 controller driver
    "nvme" # NVMe SSD driver
    "ahci" # AHCI driver
    "usb_storage" # USB storage driver
    "usbhid" # USB Human Interface Devices driver for keyboard
    "sd_mod" # SCSI driver
  ];
  boot.kernelModules = [ "kvm-intel" ];
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = true;

  # ZFS
  # Enable ZFS
  boot.supportedFilesystems = [ "zfs" ];
  # The doc says it should be set to false.
  # https://search.nixos.org/options?channel=25.11&query=boot.zfs&show=boot.zfs.forceImportRoot
  boot.zfs.forceImportRoot = false;
  # The doc says ZFS requires this.
  # https://search.nixos.org/options?channel=25.11&query=ZFS&show=networking.hostId
  # This was generated with `head -c 8 /etc/machine-id`
  networking.hostId = "0c1b9b5d";

  swapDevices = [
    {
      device = "/dev/disk/by-label/swap";
    }
  ];
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };
  fileSystems."/data" = {
    # This has to be a pool name, not an absolute path.
    device = "data";
    fsType = "zfs";
  };

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  time.timeZone = "Asia/Hong_Kong";
  i18n.defaultLocale = "en_US.UTF-8";

  networking.hostName = "nas";
  networking.networkmanager.enable = true;
  networking.firewall.enable = true;
  services.openssh.enable = true;
  services.tailscale.enable = true;

  security.sudo.wheelNeedsPassword = false;

  users.users.nixos = {
    isNormalUser = true;
    extraGroups = [
      "wheel"
      "networkmanager"
    ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID10oX/o5t2FBc/DYIQMLqpmUYzFMiGebCtYCG0B1ik+ openpgp:0x5B63D933"
    ];
  };

  environment.systemPackages = with pkgs; [
    vim
    git
  ];

  # Usage:
  #   nh os switch
  programs.nh.enable = true;
  programs.nh.flake = "/home/nixos/dotfiles";
}
