;;; init-keymap.el --- init-keymap.el -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:

;; We want to be able to bind different commands to the physical tab and the physical control-i.
;; Here are the facts we need to know.
;;
;; Fact 1: In Emacs, C-i === TAB === 8, and C-m === RET === 13
;; Fact 2: <tab> and <return> are function keys.
;; Fact 3: <tab> is mapped to [9], and <return> is mapped to [13] in `function-key-map' by default.
;; Fact 4: Most packages map their commands to `TAB' and `RET'.
;; Fact 5: Most packages never map `<tab>' and `<return>'.
;; Fact 6: evil-mode by default map ESC in decode-input-map.
;;         See https://github.com/emacs-evil/evil/blob/1.14.2/evil-core.el#L592
;;
;; Conclusion 1: We want the physical tab to mean TAB, so that most packages are not broken.
;;               By default the event generated by the physical tab key is `<tab>'.
;;               This means we must translate `<tab>' into [9].
;; Conclusion 2: We want the physical control-i to mean something other than [9], so that we can map it different from `<tab>'.
;;               We could map it to `<tab>', if if a package really bind `<tab>', not `TAB', then it is broken.
;;               Therefore, it is better to translate it to a brand new function key, such as `<control-i>'.
;;               I believe no package out there bind it.
;; Conclusion 3: In general, we want to the physical key and its control sequence mean different things, so they can be bound differently.
;;               This means we want to apply the same logic to the following pairs:
;;               - `<return>' and `RET'
;;               - `<tab>' and `TAB'
;;               `<escape>' and `ESC' are left intact because evil-mode has some hack on it. See Fact 6.
;; Conclusion 4: With the following setup, here is what happens what the physical tab is pressed.
;;               Physical Tab -> <tab> -> TAB -> execute whatever command bound to TAB.
;;               Physical control-i -> TAB -> <control-i> -> execute whatever command bound to <control-i> (which should be none because it is brand new).
;;               Physical Return -> <return> -> RET -> execute whatever command bound to RET.
;;               Physical control-m -> RET -> <control-m> -> execute whatever command bound to <control-m> (which should be none because it is brand new).
;;               This also means no physical keys can generate <tab> and <return> anymore.
;;               This is not a problem due to Fact 5.
;;
(keymap-unset function-key-map "<tab>" t)
(keymap-set key-translation-map "TAB" [control-i])
(keymap-set key-translation-map "<tab>" [9])

(keymap-unset function-key-map "<return>" t)
(keymap-set key-translation-map "RET" [control-m])
(keymap-set key-translation-map "<return>" [13])

;; Rebind C-x C-b to buffer-menu.
;; This is a recommendation in eintr section 16.7.
(keymap-global-set "<remap> <list-buffers>" #'buffer-menu)

(provide 'init-keymap)
;;; init-keymap.el ends here
