;;; init-keymap.el --- init-keymap.el -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:

;; We want to be able to bind different commands to tab and CTRL-i.
;; Here are the facts we need to know.
;;
;; Fact 1: C-i === TAB === 9
;; Fact 2: <tab> is a function key.
;; Fact 3: <tab> is mapped in function-key-map to [9] by default.
;; Fact 4: Most packages map their command to `TAB'.
;; Fact 5: Most packages never map `<tab>'.
;;
;; Conclusion 1: We want the physical tab key to mean C-i, so that most packages are not broken.
;;               By default the event generated by the physical tab key is `<tab>'.
;;               This means we must translate `<tab>' into [9].
;; Conclusion 2: We want C-i to something other than [9], so that we can map it different from `<tab>'.
;;               We could map it to `<tab>', if if a package really bind `<tab>', not `TAB', then it is broken.
;;               Therefore, it is better to translate it to something brand new, like `<control-i>'.
;;               `<control-i>' is a brand new function key.
;;               I believe no package out there bind it.
;;
;; Step 1: Undo Fact 3.
(keymap-unset function-key-map "<tab>" t)
;; Step 2: Make `C-i' means `<control-i>'
(keymap-set key-translation-map "C-i" [control-i])
;; Step 3: Make `<tab>' means `C-i'
(keymap-set key-translation-map "<tab>" [9])

;; Rebind C-x C-b to buffer-menu.
;; This is a recommendation in eintr section 16.7.
(keymap-global-set "<remap> <list-buffers>" #'buffer-menu)

(provide 'init-keymap)
;;; init-keymap.el ends here
