version: 2
tools:
  eslint: &eslint
    lint-command: "npx --no-install --quiet eslint --format visualstudio --stdin --stdin-filename ${INPUT}"
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
    - "%f(%l,%c): %tarning %m"
    - "%f(%l,%c): %rror %m"
  golangci-lint: &golangci-lint
    lint-command: "golangci-lint run --out-format=line-number --print-issued-lines=false --fast"
  gofmt: &gofmt
    format-command: 'gofmt -s'
    format-stdin: true
languages:
  go:
  - <<: *golangci-lint
  - <<: *gofmt
  javascript:
  - <<: *eslint
  javascriptreact:
  - <<: *eslint
  javascript.jsx:
  - <<: *eslint
  typescript:
  - <<: *eslint
  typescriptreact:
  - <<: *eslint
  typescript.jsx:
  - <<: *eslint
