version: 2
tools:
  eslint: &eslint
    lint-command: "npx --no-install --quiet eslint --format visualstudio --stdin --stdin-filename ${INPUT}"
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
    - "%f(%l,%c): %tarning %m"
    - "%f(%l,%c): %rror %m"
  golangci-lint: &golangci-lint
    lint-command: "golangci-lint run --out-format=line-number --print-issued-lines=false --fast"
  gofmt: &gofmt
    format-command: 'gofmt -s'
    format-stdin: true
  shellcheck: &shellcheck
    lint-command: 'shellcheck --format=gcc --color=never --shell=sh --enable=all --external-sources'
    lint-formats:
    - '%f:%l:%c: %trror: %m'
    - '%f:%l:%c: %tarning: %m'
    - '%f:%l:%c: %tote: %m'
  prettier-js: &prettier-js
    format-command: "npx --no-install --quiet prettier"
languages:
  sh:
  - <<: *shellcheck
  go:
  - <<: *golangci-lint
  - <<: *gofmt
  javascript:
  - <<: *eslint
  - <<: *prettier-js
  javascriptreact:
  - <<: *eslint
  - <<: *prettier-js
  javascript.jsx:
  - <<: *eslint
  - <<: *prettier-js
  typescript:
  - <<: *eslint
  - <<: *prettier-js
  typescriptreact:
  - <<: *eslint
  - <<: *prettier-js
  typescript.jsx:
  - <<: *eslint
  - <<: *prettier-js
