add_newline = true
follow_symlinks = false
# I used to add git information to the prompt,
# but it turns out it slows down the prompt in very large repository like nixpkgs.
format = "${custom.osc133start}$jobs$kubernetes$python$direnv$shell@$shlvl\n$status ${custom.osc7}"

[character]
disabled = false
error_symbol = "[I](bold green)"
format = "$symbol"
success_symbol = "[I](bold green)"
vimcmd_replace_one_symbol = "[R](bold green)"
vimcmd_replace_symbol = "[R](bold cyan)"
vimcmd_symbol = "[N](bold red)"
vimcmd_visual_symbol = "[V](bold purple)"

[direnv]
disabled = false
format = "[$loaded]($style)"
loaded_msg = "(direnv)"
unloaded_msg = ""

# When I press <C-z> to background nvim,
# I would like to remind myself about this.
#
# FIXME: starship jobs does not work on nushell
# Seehttps://starship.rs/config/#jobs
[jobs]
symbol_threshold = 1
number_threshold = 1
format = "[\\($number$symbol\\)]($style)"

[kubernetes]
disabled = false
format = "[\\($context\\)]($style)"

[python]
disabled = false
format = "[\\($virtualenv\\)]($style)"

[shell]
disabled = false
format = "[$indicator]($style)"
bash_indicator = "bash"
elvish_indicator = "elvish"
fish_indicator = "fish"
nu_indicator = "nu"
unknown_indicator = "unknown"

[shlvl]
disabled = false
format = "[$shlvl](bold yellow)"
threshold = 0

[status]
disabled = false
format = "$symbol"
not_executable_symbol = "[$status \\$](bold red)"
not_found_symbol = "[$status \\$](bold red)"
sigint_symbol = "[$status \\$](bold red)"
signal_symbol = "[$status \\$](bold red)"
success_symbol = "\\$"
symbol = "[$status \\$](bold red)"

[custom.osc7]
disabled = false
when = 'true'
unsafe_no_escape = true
format = "$output"
command = ''' printf "\033]7;file://$PWD\033\\" '''

# Taking "$GHOSTTY_RESOURCES_DIR"/shell-integration/fish/vendor_conf.d/ghostty-shell-integration.fish as reference
# It only emits `Escape 133 ; A ST`.
# And in my testing with Neovim terminal-mode [[ and ]]
# omitting that seems enough.
# No need to emit `Escape 133 ; B ST`.
[custom.osc133start]
disabled = false
when = 'true'
unsafe_no_escape = true
format = "$output"
command = ''' printf "\033]133;A\007" '''
