[output]
show_title = true
platform_title = true
show_hyphens = false
compact = true

[indent]
title = 2
description = 2
bullet = 2
example = 4

[style.title]
color = "default"
background = "default"
bold = true
underline = false
italic = false
dim = false
strikethrough = false

[style.description]
color = "default"
background = "default"
bold = false
underline = false
italic = false
dim = true
strikethrough = false

[style.bullet]
color = "default"
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.example]
color = "default"
background = "default"
bold = false
underline = false
italic = false
dim = true
strikethrough = false

[style.url]
color = "default"
background = "default"
bold = false
underline = true
italic = false
dim = true
strikethrough = false

[style.inline_code]
color = "default"
background = "default"
bold = false
underline = false
italic = true
dim = true
strikethrough = false

[style.placeholder]
color = "default"
background = "default"
bold = false
underline = false
italic = true
dim = true
strikethrough = false
