{
  pkgs,
  config,
  lib,
  ...
}:
{
  programs.git.ignores = [
    ".claude/settings.local.json" # https://code.claude.com/docs/en/settings#available-scopes
  ];

  home.packages = with pkgs; [
    # From the overlay of natsukium/mcp-servers-nix
    #
    # As of 2025-06-08, Playwright supports full page screenshot out-of-the-box.
    # https://playwright.dev/docs/screenshots#full-page-screenshots
    # But @playwright/mcp does not expose that
    # https://github.com/microsoft/playwright-mcp/blob/v0.0.28/src/tools/screenshot.ts
    playwright-mcp

    # From the overlay of natsukium/mcp-servers-nix
    context7-mcp
  ];
  programs.mcp.enable = true;
  programs.mcp.servers = {
    playwright = {
      command = "${config.home.profileDirectory}/bin/mcp-server-playwright";
    };
    context7 = {
      command = "${config.home.profileDirectory}/bin/context7-mcp";
    };
  };

  programs.claude-code.enable = true;
  programs.claude-code.enableMcpIntegration = true;
  programs.claude-code.memory.text = ''
    # CLAUDE.md

    ## Use Bash tool

    Try using your Bash tool when you lack the ability to do something relevant to your task.

    Here are some examples:

    - In a Python script, you gain access to a cryptographically secure RNG.
    - In a Python script, you gain access to datetime utility and calendar manipulation.

    ## Date format

    Unless otherwise specified, output date and time in ISO 8601 format.

    Examples:
    - `2006-01-02`
    - `2006-01-02T15:04:05Z`
    - `2006-01-02T15:04:05.999+07:00`

    ## Reading PDF files

    In case you cannot read PDF files, you should use the markitdown tool to do so.

    ## Manipulate PDF files

    Use poppler-utils instead of pdftk to manipulate PDF files.
  '';

  # It was observed that since 2026-04-10, Claude Desktop writes to claude_desktop_config.json
  # on every launch.
  # That would replace the symlink generated by home-manager by a regular file.
  # The home-manager switch will fail.
  # So we use activation to write a regular file.
  home.activation.claude-desktop =
    let
      claude_desktop_config = pkgs.writeText "claude_desktop_config.json" (
        builtins.toJSON {
          preferences = {
            quickEntryShortcut = "off";
            # The following settings were added by Claude Desktop.
            # I just copied them here.
            sidebarMode = "chat";
            coworkWebSearchEnabled = false;
            coworkScheduledTasksEnabled = false;
            ccdScheduledTasksEnabled = false;
          };
        }
      );
    in
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      cp ${claude_desktop_config} ${config.home.homeDirectory}"/Library/Application Support/Claude/claude_desktop_config.json"
      chmod 600 ${config.home.homeDirectory}"/Library/Application Support/Claude/claude_desktop_config.json"
    '';
}
