return {
  {
    'nvim-treesitter/nvim-treesitter',
    main = 'nvim-treesitter.configs',
    opts = {
      ensure_installed = {
        "bash",
        "css",
        "dart",
        "dockerfile",
        "fish",
        "go",
        "gomod",
        "gowork",
        "graphql",
        -- "help",
        "html",
        "http",
        "java",
        "javascript",
        "json",
        "json5",
        "kotlin",
        "lua",
        "make",
        "ocaml",
        "ocaml_interface",
        "ocamllex",
        "python",
        "regex",
        "rust",
        "scss",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "yaml",
      },
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
      },
    },
  },
}
