{
  pkgs,
  config,
  lib,
  ...
}:
{
  programs.git.ignores = [
    ".claude/settings.local.json" # https://code.claude.com/docs/en/settings#available-scopes
  ];

  programs.claude-code.enable = true;
  programs.claude-code.enableMcpIntegration = false;
  programs.claude-code.context = ''
    ## Date format

    Unless otherwise specified, output date and time in ISO 8601 format.

    Examples:
    - `2006-01-02`
    - `2006-01-02T15:04:05Z`
    - `2006-01-02T15:04:05.999+07:00`
  '';

  # It was observed that since 2026-04-10, Claude Desktop writes to claude_desktop_config.json
  # on every launch.
  # That would replace the symlink generated by home-manager by a regular file.
  # The home-manager switch will fail.
  # So we use activation to write a regular file.
  home.activation.claude-desktop =
    let
      claude_desktop_config = pkgs.writeText "claude_desktop_config.json" (
        builtins.toJSON {
          preferences = {
            quickEntryShortcut = "off";
            # The following settings were added by Claude Desktop.
            # I just copied them here.
            sidebarMode = "chat";
            coworkWebSearchEnabled = false;
            coworkScheduledTasksEnabled = false;
            ccdScheduledTasksEnabled = false;
          };
        }
      );
    in
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      cp ${claude_desktop_config} ${config.home.homeDirectory}"/Library/Application Support/Claude/claude_desktop_config.json"
      chmod 600 ${config.home.homeDirectory}"/Library/Application Support/Claude/claude_desktop_config.json"
    '';
}
